### ISSUE TITLE
Highlight 'unknown' mentions (no suggestion) e.g. not (yet) existing #tags

### ISSUE THREAD

**Issue by hartmut-co-uk** [heyscrumpy/tiptap#108]
As a user I'd like to be able to enter #tags with an autocomplete / suggest experience - while similar to when creating a tweet - any #hashtag #nonExisting #newOnes matching the valid syntax / pattern would render / be formatted same as existing suggestions (mentions).

Ideally would work as well if 'some #text is pasted' into the editor, too -> highlighting the contained #text tag.

Does this make sense?

**Comment by ilicmarko** [comment]
This introduces one concern, how do you differentiate it from a real mention? Further more this complete changes the idea of mention, autocomplete from a list entities.

You can probably do this with a custom node, just add that that node `span` isn't `contenteditable`, this means when you try to delete it will delete it a as a whole, not letter by letter.

**Comment by hartmut-co-uk** [comment]
Thanks for your response and the hint. I might not need/want to wrap it with a span / have it to delete in one go - similar to twitter it should be a fluent part of the _text_ and delete character by character rather than the solid mentions as they exist right now - the most important feature would be the autocomplete.. 
But I'm currently still evaluating & designing how I'd like my editor to work / look like (UX). 
The _renderless_ approach + extensions + overall design of tiptap is just amazing and seems to leave room for almost any kind of feature you'd want to implement. 🏅 👏

**Comment by philippkuehn** [comment]
Hey @hartmut-co-uk. You can use a modified version of the `Mention` extension for that. In my opinion it's good to store always an id of a mention (`{ id: 123, label: 'username' }`) instead of just a string (`username`). But in your case for hashtags this is maybe something different. While typing you can suggest something (and maybe fetch some entries from an API or something) but on paste this way more complicated. In the latest version I added `pasteRules` for converting text to nodes on pasting – similar to `inputRules` for converting text to nodes on typing. You can see this pasteRules in action in the default [Link node](https://github.com/heyscrumpy/tiptap/blob/master/packages/tiptap-extensions/src/marks/Link.js#L44).

**Comment by philippkuehn** [comment]
Okay, so I'm closing this because I think it's possible with the current implementation of the Suggestions plugin.

**Comment by andreasvirkus** [comment]
@philippkuehn sorry to bring up an old thread, but how would you go about using the Mention extension for this feature (while still also using `@mentions` as well)?
