### ISSUE TITLE
Changing prepend symbol within Mention Node

### ISSUE THREAD

**Issue by jazerix** [heyscrumpy/tiptap#75]
I can't for the life of me seem to figure out, how I can change the **@** symbol to something else within the vue component. 

I've been able to register the trigger to be **%** by overriding the matcher property
`matcher: {
    char: "%",
    allowSpaces: false,
    startOfLine: false
},`

I'm sorry if this has been asked before, but is there any way to change the @ symbol that automatically gets appended to the tags? 

I would also love to be able to append another symbol.

Cheers! :)

**Comment by ianfabs** [comment]
I've been encountering the same issue, with no way around it in my current setup, since I am using http://codesandbox.io/. In my case, I am looking to make the character disappear entirely after hitting enter.

I did however, notice something in their source code, [here](https://github.com/heyscrumpy/tiptap/blob/master/packages/tiptap-extensions/src/plugins/Suggestions.js) that suggests if you could modify this in your node_modules, you could change it. Here is the line that you would need to change:
```js
6   |  function triggerCharacter({
7   |	   char = '@',    // <----- This would become * char = '%' *
8   |	   allowSpaces = false,
9   |	   startOfLine = false,
10  |  }) {
```

While there is another place on line 62 that has an `@` symbol, I believe it to be understandably inferred that _this_ is the option that gets changed with the `matcher` parameter

**Comment by philippkuehn** [comment]
Hey, you don't have to change anything in `Suggestions.js`. There is already an option for changing the char in the Mentions Node. But you're right – I was missing something to replace. I releases a new version of `tiptap-extensions` in this moment. Everything you need to do is:

```js
new MentionNode({
    matcher: {
       char: '%',
    },
})
```

Please keep in mind that you can't use multiple instances of a node. So if you want to use the Mention Node multiple times with different settings you have to create a copy of that Node. Just take that copy from the `tiptap-extensions` folder in this repo.

**Comment by reubenv** [comment]
> I've been encountering the same issue, with no way around it in my current setup, since I am using http://codesandbox.io/. In my case, I am looking to make the character disappear entirely after hitting enter.

I know this is closed, but was just wondering if anyone ever sorted out a way to do exactly what @ianfabs mentions here? Specifically "... looking to make the character disappear entirely after hitting enter."

If I want to mention 'reubenv', and I start with '@reu', find the mention I want to add, when I click on it or hit enter, I want it to be inserted as 'reubenv' and NOT '@reubenv'. 

Any help?
