### ISSUE TITLE
Generic align for paragraphs, headings, lists...

### ISSUE THREAD

**Issue by leandromatos** [heyscrumpy/tiptap#80]
It's possible to align others elements? Like any paragraphs, headings or maybe lists?

That's example only align paragraphs https://github.com/heyscrumpy/tiptap/tree/master/examples/Components/Routes/TextAlign

**Comment by philippkuehn** [comment]
After some thinking I decided to **not** supporting all styling nodes like text alignment, font family or font color in this core packages. Maybe someone will create some extension for that.

**Comment by leandromatos** [comment]
OK man. In my next project maybe I can use the TipTap, because in this time i need use more tools.

**Comment by patrikengborg** [comment]
Hi,

First of all, great work with tiptap! I just switched from Quill.

I wanted to ask is if you could reconsider your decision to not include alignment support? It's the one thing I really miss, and I've been spending several hours trying to get it right myself, but I'm struggling to come up with a complete working solution. Mostly because of ProseMirror's somewhat complex API and docs.

I totally get why you chose to not include font family and colors, but text aligmnent feels very fundamental for an editor. It seems other people are missing this feature too.

So it would be amazing if you could include alignment support, I would be really thankful for it.

Let me know what you think. Thanks!

**Comment by philippkuehn** [comment]
Hey @patrikengborg,

one time there was an example for adding alignments to paragraphs. That was easy because we could just add some different paragraph styles. But it gets more complicated if you try to select multiple nodes (paragraph, headings, lists, custom nodes, …) and want to align them, because then every node needs to have an alignment option (defined as `attrs` in the schema). I'm not sure if there is a clever way to achieve this but for the moment I do not try to solve this. If anyone else has an idea, I'm very excited to hear it. ✌️
