### ISSUE TITLE
Consider adding a changelog

### ISSUE THREAD

**Issue by erickwilder** [heyscrumpy/tiptap#97]
I've been following the latest updates but sometimes there's no description in the GitHub releases tab.

Consider adopting a changelog strategy, be it automatically generated (i.e., semantic release) or manually curated (i.e., https://keepachangelog.com)

**Comment by philippkuehn** [comment]
Hey @erickwilder,

yeah I try to improve that. I think for the `tiptap` core package there is almost always a description but for the other packages there isn't. This is because I'm using lerna for publishing. Whenever I update `tiptap`, there is also an update for `tiptap-extensions` because it's a dependency and so on. But maybe I should add a description that I've updated the dependencies 😅

**Comment by erickwilder** [comment]
Semantic release does support Lerna BTW.

**Comment by darkman97i** [comment]
I have been looking for changelog but I have not been able to find it. Do you have? In github projects usually is added ChangeLog.md file, but seems is not present it in your project. Doing a wide search in your documentation I have not been able to find in your documentation.

If you decide to do not have one, consider creating milestone, because for each milestone then is possible to check the changes - issues - what has been done, seems you do not have milestone created.

Thanks for your time.

**Comment by kelunik** [comment]
Kind reminder, https://github.com/ueberdosis/tiptap/compare/tiptap%401.30.0...tiptap%401.31.0 is pretty verbose and contains a lot of things not relevant to the release. Or does a changelog exist now and I missed it?

**Comment by hanspagel** [comment]
Nope, there’s still no changelog. Sorry! 😏 That’s what I kept manually in my notes for the release:

* dependencies updated
* merged: Links use their individual target now https://github.com/ueberdosis/tiptap/pull/902
* merged: Tables: setCellAttrs has parameters now https://github.com/ueberdosis/tiptap/pull/883/files
* merged: Can not copy inserted mention https://github.com/ueberdosis/tiptap/pull/861

And yes, we should have a changelog. 😬 Good news though: tiptap v2 comes with changelogs for all packages.
